"""THE canonical per-(gene, arm) card — ONE object, TWO provenance-tagged estimator blocks joined on
``(gene, arm)``. Supersedes the orphan ``arm_attribution_card.tsv`` (deleted) and unifies the two live
card families that the 2026-07-18 duplication audit found could NOT share a row.

  ┌─ ATTRIBUTION block ──────────────────────────────────────────────────────────────────────────┐
  │ estimator: DENSE GIBBS posterior mean β (half-normal slab, π≡1) + Shapley/LMG identity on      │
  │            bagged-NNLS weights.  Source: ``learned/readouts.py`` (``readouts_arm_edges.tsv``).  │
  │ columns:   beta, beta_sd, z, identified, identity, m_nnls, beta_frac(, _sd), pip_dense,         │
  │            pip_discovery, prior_pi, beta_deconv, retention_beta, composition_class,             │
  │            net_pressure, seed_family, family_size, detection, ago_loading                       │
  └───────────────────────────────────────────────────────────────────────────────────────────────┘
  ┌─ PROGRESSION block ──────────────────────────────────────────────────────────────────────────┐
  │ estimator: bagged-NNLS ``canonical_M`` budget (rank/share) + PARTIAL-SPEARMAN ρ 3-state         │
  │            coupling (GTEx→NAT→tumour).  Source: ``learned/card.py::gene_card``.                 │
  │ columns:   share_TUM, rank_TUM, d_rank_HLY_TUM, grank_{HLY,NAT,TUM}, arm_lfc_*,                 │
  │            coupling_{hly,nat,tum}, retention_rho, spiker, arm_med_rpm/pct_floor/iqr, shift_class│
  └───────────────────────────────────────────────────────────────────────────────────────────────┘

⚠ THE TWO BLOCKS CARRY DIFFERENT M's (Gibbs β ≠ bagged-NNLS ≠ partial-ρ). They are JOINED, never merged
into a single weight. `retention_beta` (Gibbs β_deconv/β_core) ≠ `retention_rho` (ρ_deconv/ρ_core).
Column→estimator provenance is persisted alongside the table (``edge_card_base_provenance.tsv``).

The PROGRESSION coupling axis carries the progression-annotation ``shift_class`` (learned partial-ρ,
level×3-state-realization×composition×detectability). It is NOT ``mirna_state_class.joint_edge_class``
(retired-pressure heuristic) — same names, different label system; never map one onto the other.

CLI (parallel; defaults to full HE-edge gene universe, ``nproc-1`` workers):
  python -m mirna_hallmark.learned.canonical_card
  python -m mirna_hallmark.learned.canonical_card --genes PTEN GATA3 --workers 4
  python -m mirna_hallmark.learned.canonical_card --reuse-attribution   # skip the readouts re-run
"""
from __future__ import annotations

# ⚡ Single-thread BLAS BEFORE numpy import — 7 workers × multi-thread BLAS on 8 cores oversubscribes to
# ~56 threads and DEADLOCKS on futex locks (workers stall at ~2% CPU). Set before pandas/numpy load.
import os as _os
for _v in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS", "NUMEXPR_NUM_THREADS",
           "VECLIB_MAXIMUM_THREADS"):
    _os.environ.setdefault(_v, "1")

import argparse
import contextlib
import io
import os
import sys
import time
from pathlib import Path
from typing import List, Optional, Sequence

import numpy as np
import pandas as pd

from mirna_hallmark import config as C
from mirna_hallmark.learned import data as LD

OUT_DIR = Path(C.OUTPUT_ROOT) / "learned"
OUT_CARD = OUT_DIR / "edge_card_base.tsv"
OUT_PROG = OUT_DIR / "progression_card.tsv"
OUT_PROV = OUT_DIR / "edge_card_base_provenance.tsv"
ATTR_SRC = OUT_DIR / "readouts_arm_edges.tsv"           # block A (regenerated by readouts.run(level="arm"))

# ATTRIBUTION columns whose names would collide with the progression block on join.
_ATTR_RENAME = {"retention": "retention_beta"}
# PROGRESSION columns whose names would collide with the attribution block on join.
_PROG_RENAME = {"retention": "retention_rho"}


# --------------------------------------------------------------------------- #
# universe
_EXCLUDE = {"GAPDH"}   # native heap-corruption ("double free") in gene_card's NNLS/BLAS on this gene's
                       # DEGENERATE design (2 HE edges, near-constant housekeeping expression). Uncatchable
                       # SIGABRT (not a Python exception); biologically inconsequential here — a miRTarBase
                       # common-control artifact. Isolated 2026-07-18; see memory batch-nfs-per-unit-reads.


def universe() -> List[str]:
    """The HE-edge target-gene universe (the genes both blocks score), minus known native-crashers."""
    he = LD.D.high_evidence_edges()
    return sorted(set(he["gene"].unique()) - _EXCLUDE)


# --------------------------------------------------------------------------- #
# PROGRESSION block — parallel batch over gene_card (the runner card.py lacked)
def _progression_chunk(genes: Sequence[str]) -> pd.DataFrame:
    """One worker: run gene_card over a gene chunk (stdout suppressed), tag with `gene`, concat.
    lru-cached loaders (GTEx/state matrices, _load, CNV matrix) warm ONCE per worker process."""
    from mirna_hallmark.learned import card as CARD
    frames = []
    for g in genes:
        try:
            with contextlib.redirect_stdout(io.StringIO()):
                df = CARD.gene_card(g)
        except Exception as e:                                  # a single bad gene must not kill the chunk
            sys.stderr.write(f"[canonical_card] gene_card({g}) failed: {e}\n")
            continue
        if df is not None and len(df):
            df = df.copy()
            df.insert(0, "gene", g)
            frames.append(df)
    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()


def build_progression(genes: Sequence[str], *, workers: int, out_path: Path = OUT_PROG) -> pd.DataFrame:
    """gene_card over the universe → the PROGRESSION block, persisted to `out_path`. workers=1 runs a single
    process (the SHARD mode used by the robust subprocess driver — no in-process Pool, which proved fragile
    on this NFS box: see memory `batch-nfs-per-unit-reads`)."""
    genes = list(genes)
    t0 = time.time()
    if workers <= 1 or len(genes) <= 1:
        prog = _progression_chunk(genes)
    else:
        from multiprocessing import get_context
        # WARM-THEN-FORK. Load every cache ONCE in the parent (a single gene_card call primes _load, the
        # GTEx/state matrices, the CNV matrix, CIBERSORTx and the healthy baseline), THEN fork — workers
        # inherit the warm caches via COW, so no worker re-reads NFS or re-parses. This avoids the spawn
        # failure mode (7 workers each re-loading the same big matrices from NFS simultaneously → thundering
        # herd → a worker dies → Pool.map hangs). Fork is safe here because BLAS is single-threaded (set at
        # import): no OpenMP threadpool exists to inherit locked, which was the ORIGINAL fork deadlock.
        from mirna_hallmark.learned import card as _CARD
        print(f"[progression] warming caches in parent (1 gene) before fork...")
        with contextlib.redirect_stdout(io.StringIO()):
            try:
                _CARD.gene_card(genes[0])
            except Exception as e:
                sys.stderr.write(f"[canonical_card] warm gene_card({genes[0]}) failed: {e}\n")
        k = min(workers, len(genes))
        chunks = [genes[i::k] for i in range(k)]              # round-robin → balanced load across workers
        with get_context("fork").Pool(processes=k) as pool:
            parts = pool.map(_progression_chunk, chunks)
        prog = pd.concat([p for p in parts if len(p)], ignore_index=True) if parts else pd.DataFrame()
    dt = time.time() - t0
    if len(prog):
        prog = prog.rename(columns=_PROG_RENAME)
        prog.to_csv(out_path, sep="\t", index=False, float_format="%.5f")
        n_g = prog["gene"].nunique()
        print(f"[progression] {len(prog)} rows / {n_g} genes in {dt:.1f}s "
              f"({dt / max(n_g, 1):.2f}s/gene, {workers}w) -> {out_path}")
    else:
        print(f"[progression] EMPTY after {dt:.1f}s")
    return prog


# --------------------------------------------------------------------------- #
# ATTRIBUTION block — regenerate (or reuse) readouts_arm_edges.tsv
def ensure_attribution(genes: Optional[Sequence[str]], *, workers: int, reuse: bool) -> pd.DataFrame:
    """Block A. Regenerate readouts at ARM level (post-MH140 schema: identity/m_nnls/beta_frac) unless
    `reuse` and the file already carries the current schema."""
    fresh_schema = ("identity" in pd.read_csv(ATTR_SRC, sep="\t", nrows=0).columns) if ATTR_SRC.exists() else False
    if reuse and fresh_schema:
        print(f"[attribution] reusing {ATTR_SRC} (current schema)")
        return pd.read_csv(ATTR_SRC, sep="\t")
    if reuse and not fresh_schema:
        print(f"[attribution] {ATTR_SRC} is PRE-MH140 (no `identity`) — regenerating despite --reuse")
    from mirna_hallmark.learned import readouts as R
    print(f"[attribution] regenerating readouts (level=arm, {workers}w)...")
    R.run(genes=list(genes) if genes else None, workers=workers, level="arm")
    return pd.read_csv(ATTR_SRC, sep="\t")


# --------------------------------------------------------------------------- #
# join + provenance
def _provenance(attr_cols, prog_cols) -> pd.DataFrame:
    rows = [("gene", "key", "join key"), ("arm", "key", "join key")]
    for c in attr_cols:
        if c in ("gene", "arm"):
            continue
        rows.append((c, "ATTRIBUTION", "dense Gibbs β / Shapley identity (readouts.py)"))
    for c in prog_cols:
        if c in ("gene", "arm"):
            continue
        rows.append((c, "PROGRESSION", "bagged-NNLS budget + partial-ρ 3-state coupling (card.py)"))
    return pd.DataFrame(rows, columns=["column", "block", "estimator"])


def _join_and_write(attr: pd.DataFrame, prog: pd.DataFrame) -> pd.DataFrame:
    card = attr.merge(prog, on=["gene", "arm"], how="outer", suffixes=("", "_prog"))
    # ⭐ DEDUCIBLE within-family identity allocation (MH-166 follow-up). β/identity are broadcast equally to same-seed
    # members; where the family is dose-DOMINATED the credit is deducibly the dominant arm's, so null it on the phantom
    # (below-floor) minor. `co` (dose-balanced) arms carry an UNVALIDATED arm split (needs breast chimeric/knockdown).
    if "identity" in card and "family_role" in card:
        _minor = card["family_role"].eq("minor")
        card["identity_allocated"] = card["identity"].mask(_minor, 0.0)          # phantom minors → 0; else family identity
        card["arm_id_status"] = np.select(
            [card["family_role"].eq("co"), card["family_role"].eq("sole")],
            ["unvalidated_balanced", "singleton"], default="resolved_by_dose")   # dominant/minor = dose-resolved
    card = card.sort_values(["gene", "beta"], ascending=[True, False], na_position="last")
    card.to_csv(OUT_CARD, sep="\t", index=False, float_format="%.5f")
    _provenance(list(attr.columns), list(prog.columns)).to_csv(OUT_PROV, sep="\t", index=False)
    n_join = card.dropna(subset=["beta", "shift_class"]).shape[0] if "shift_class" in card else 0
    print(f"[canonical_card] {len(card)} (gene,arm) rows | {card['gene'].nunique()} genes | "
          f"both-block rows {n_join} -> {OUT_CARD}\n  provenance -> {OUT_PROV}")
    return card


def join_from_files() -> pd.DataFrame:
    """--join-only: join the already-built block A (readouts_arm_edges) + the assembled progression_card.tsv
    (concatenated from the subprocess shards) into the canonical card. Pure join, no compute."""
    if not ATTR_SRC.exists() or not OUT_PROG.exists():
        print(f"[join] missing input: attr={ATTR_SRC.exists()} prog={OUT_PROG.exists()}"); return pd.DataFrame()
    attr = pd.read_csv(ATTR_SRC, sep="\t").rename(columns=_ATTR_RENAME)
    prog = pd.read_csv(OUT_PROG, sep="\t")
    return _join_and_write(attr, prog)


def build(genes: Optional[Sequence[str]] = None, *, workers: int = max(1, (os.cpu_count() or 2) - 1),
          reuse_attribution: bool = False) -> pd.DataFrame:
    genes = list(genes) if genes else universe()
    print(f"=== canonical two-block card: {len(genes)} genes, {workers} workers ===")
    attr = ensure_attribution(genes, workers=workers, reuse=reuse_attribution).rename(columns=_ATTR_RENAME)
    attr = attr[attr["gene"].isin(genes)] if "gene" in attr.columns else attr
    prog = build_progression(genes, workers=workers)
    if not len(prog):
        print("[canonical_card] no progression rows — aborting join"); return pd.DataFrame()
    return _join_and_write(attr, prog)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--genes", nargs="*", default=None)
    ap.add_argument("--workers", type=int, default=max(1, (os.cpu_count() or 2) - 1))
    ap.add_argument("--reuse-attribution", action="store_true",
                    help="reuse readouts_arm_edges.tsv if it already carries the current (identity) schema")
    ap.add_argument("--prog-out", type=Path, default=None,
                    help="SHARD mode: run progression on --genes single-process, write to this path, no join")
    ap.add_argument("--join-only", action="store_true",
                    help="join existing block A + progression_card.tsv into the canonical card (no compute)")
    a = ap.parse_args()
    if a.prog_out is not None:                                   # subprocess shard (robust parallel driver)
        build_progression(a.genes or universe(), workers=1, out_path=a.prog_out)
        return
    if a.join_only:
        join_from_files(); return
    build(genes=a.genes, workers=a.workers, reuse_attribution=a.reuse_attribution)


if __name__ == "__main__":
    main()
